Fix memcached error parsing
Problem
parseErrorMessage only returns the last string, instead of the entire message.
i.e. FAT [20150721-20:26:43.792] memcache: com.twitter.finagle.memcached.protocol.ServerError: object

Solution
Parse all of the tokens instead of the head.

Result
com.twitter.finagle.memcached.protocol.ServerError: out of memory storing object

Signed-off-by: Vladimir Kostyukov <vkostyukov@twitter.com>

RB_ID=719993